### ISSUE TITLE
error loading sample data

### ISSUE THREAD

**Issue by goterm** [gbaquer3/rMSIcleanup#19]
Hi,

I am try to use the sample data provided but after loading your peak matrix (pks<-rMSIproc::LoadPeakMatrix()) the line:
full<-rMSI::LoadMsiData("path/data.tar")

returns this error:
Loading Image...
No datacube.RImg in ramdisk, new ramdisk will be created
  |                                                                                                            |    0%
**Error in system(cmd, intern = TRUE) : 'unzip' not found**

The rMSI::LoadMsiData() works with other data (.imzML).

Any idea where is this error coming from?

Thanks!

**Comment by goterm** [comment]
It turned out to be an Rtools issue. Rtools has to be in the system PATH.

**Comment by gbaquer** [comment]
Hi Goterm,

I missed the initial notification of the issue. Glad to hear you managed to solve it.

Let me know if you encounter any other issues.

Thanks,
Gerard
